# Generated by Django 3.2.6 on 2021-12-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestock', '0002_auto_20211208_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Approved'),
        ),
    ]
